[package]
name = "clicky"
version = "0.1.0"
authors = ["Maxim Schepelin <m.schepelin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk="0.8.1"
